### ISSUE TITLE
Throws NoSuchMethodError when calling getSubTypesOf(Object.class)

### ISSUE THREAD

**Issue by IEnoobong** [ronmamo/reflections#264] opened 2019-04-12 13:06 UTC
Throws `java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;`

Version 1.9.11

```java
final Reflections reflections = new Reflections(pojoPackage, new SubTypesScanner(false));
final Set<Class<?>> subTypesOf = reflections.getSubTypesOf(Object.class);
```

**Comment by stefan2904** [comment] 2019-09-30 14:15
I also get this error when trying to get all implementations of a interface:

```java
        Reflections reflections = new Reflections("foo.precheck");
        return reflections.getSubTypesOf(Prechecker.class);
```

(The current version is 0.9.11, btw.)

**Comment by stefan2904** [comment] 2019-09-30 14:20
Probably a duplicate of #194. 

So going back to version 0.9.10 "fixed" this for me. Not nice, but at least it works.

**Comment by ronmamo** [comment] 2020-01-12 15:00
fixed on 0.9.12

**Closed by ronmamo** 2020-01-12 15:00 UTC

**Comment by eyugod** [comment] 2020-01-14 06:45
why the NoSuchMethodError is happen?because of the guava version?

**Comment by ljacqu** [comment] 2020-01-14 07:25
Yes it was due to a Guava version clash and Guava is now removed altogether in the newest version
