### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by spectejb** [ronmamo/reflections#159] opened 2017-01-26 22:34 UTC
The .pom file lists both the WTFPL and the 2-clause BSD licenses.  However, the README file only lists the WTFPL license.  

Any insight on which license(s) will govern is much appreciated!

**Comment by spectejb** [comment] 2017-02-02 22:10
@ronmamo - just following up on the license question above.

**Comment by ronmamo** [comment] 2017-02-03 08:06
Not dealing with governance or licensing trolling... As the license states, you can basically do whatever you want. Feel free to fork and change the sources/license as you wish. 
HTH :)

**Comment by spectejb** [comment] 2017-02-03 14:43
I completely understand that you want to make it available to everyone (and appreciate it!).  

Our company is very supportive of associates using Open Source.  However, there are unfortunately some issues with licenses like the WTFPL that seem to dedicate open source software to the public domain.  

If interested in reading about the specific issues, see [OSI's section on software in the "public domain"](https://opensource.org/faq#public-domain).  At a high level, the issues relate to different jurisdictions interpreting "public domain" differently and this conflicts with the idea that open source should be an international solution that does not require a jurisdiction-by-jurisdiction analysis.  

However, the good news is that we could use the 2-clause BSD license.  Since the .pom file lists the 2-clause BSD, would you consider adding that to the README file as an alternative to the WTFPL?

**Comment by ronmamo** [comment] 2017-02-03 15:53
You insist on talking in a governance/lawyer language with me, where I consciously insist on opting out from that! 
I'd just say - I'm not dealing with license trolling, I'm doing software and SHARING it with anyone, freely. I don't care about any corporate/enterprise rationals regarding governance and compliance. I encourage any developer to opt out from that narrative as well, and to SHARE software freely.
A lot can be learned from the Open Source movement, I didn't see any kind of SHARING in that measure anywhere - and "we" should keep it clean from lawyers.

"Fire everyone, keep the coders" (CloudBees')

(I kinda like this kind of conversations, so I apologize for the Non-conformism. I take it with a healthy sense of humor...)

**Comment by spectejb** [comment] 2017-02-03 18:48
No apologies necessary - I was just trying to see if we could make the README file consistent with the .pom file so we could use Reflections (without any governance/lawyer concerns).   Figured no harm in asking. 

The governance/lawyer language was just bringing in some of the community discussion on the topic. :)

**Comment by ronmamo** [comment] 2017-02-04 07:55
Thank you for the good spirit.

> The governance/lawyer language was just bringing in some of the community discussion on the topic. :)

Yes. This is a community discussion in deed. Lot's of interesting conversation in Github and elsewhere regarding WTFPL, and many times are funny and stretched ad absurdum - still serious.

Please, bring in some of the community voices on the topic... 

@samhocevar

**Comment by samhocevar** [comment] 2017-02-04 16:24
I agree with a lot of what was said here. Overlawyering is a scary disease; we need our own crosses an garlic to repel it. The wording in the WTFPL deliberately helps keeping the lawyers away and that is a good thing.

@ronmamo Here’s one thing that works for me: ask for $1000 (or whatever you think your efforts are worth) for a custom version of your WTFPL software under a different license such as MIT or BSD. It’s a definite win for everyone.

**Comment by spectejb** [comment] 2017-02-05 13:43
Thanks for sharing, @samhocevar.  The Reflections .pom file actually already has BSD listed as an alternative.  My question was not to change the license and remove WTFPL altogether - it was just to add BSD to the README file to make it consistent with the .pom file. 

(Also, staying in line with ronmamo's mindset to take this conversation with a sense of humor) Isn't asking for money going against the main principle of sharing the software freely with everyone. :)

**Comment by ronmamo** [comment] 2017-02-05 19:34
(thanks for keeping with the mindset)

@samhocevar, I can't be believe you suggested to ask for money... you used to be my hero ;)

and @spectejb, the issue is not the pom file (common!), but the **lawyerly gobbledegook reality**. Why can't you accept WTFPL?! Please, just a simple answer, and try to see the non sense.

Again, please bring in some of the community voices on the topic...

@liqweed

**Comment by spectejb** [comment] 2017-02-06 23:12
Simply put, WTFPL does not let me do WTF I want when I am using it on an international level.  Since it is not recognized as a valid license everywhere, it goes against one of the most important principles of open source - the freedom to run the program as we wish, for any purpose.  

The OSI refuses to put the WTFPL on its accepted list of licenses for this reason. 

I definitely respect @samhocevar's concern about overlawyering and wanting a license that keeps the lawyers away.  If anything, the WTFPL does the opposite because there is a lot of grey area regarding its interpretation.  The BSD would, however, achieve both of @samhocevar's goals.

**Comment by spectejb** [comment] 2017-02-13 19:21
@ronmamo - Did that help illustrate why adding the BSD license could potentially increase adoption of reflections?  You can still keep the WTFPL as an option for people to choose. :)

**Comment by BMillsVT** [comment] 2017-02-27 15:23
Disclaimer: I am a lawyer (sorry). 

@ronmamo @samhocevar What's the real issue with choosing a different license?  I understand the desire to not "over lawyer" everything, but (like it or not) the WTFPL causes all sorts of consternation at corporations.  Lawyers can be overly cautious to a silly degree, but we don't like the WTFPL for valid reasons.  If you want companies to use your software, why not change the license to MIT or BSD (or add them one of them as an alternative)?  Both of those licenses accomplish what you're trying to do with the WTFPL **_and_** keep lawyers happy.   Who wouldn't want to keep lawyers happy? ;)

**Comment by samhocevar** [comment] 2017-02-28 13:32
I understand your point. I write free software for free. But keeping the lawyers happy? Someone has to pay me for that.

**Comment by spectejb** [comment] 2017-03-22 02:44
Forgetting the lawyers for a second (or longer) - can we make the developers happy and add BSD license to the README file as another option?

**Comment by davemeurer** [comment] 2017-04-05 17:57
Hello, @ronmamo: I wanted to agree with @spectejb and add that we have a similar issue.  This is what we received from legal when reviewing the WTF license:

> It doesn't cover anything that I can see. It doesn't say I am granted a right to copy, distribute, or modify the associated code. Only that I have these rights for the license file itself. The only part which could be read as pertaining to my rights over the code is "You just DO WHAT THE FUCK YOU WANT TO." That doesn't clearly grant me those rights or any rights, it just tells me to do what I like. It doesn't specify any rights that the copyright holder is waiving or granting under the terms of the license; and it can't reasonably be construed to say that the copyright holder disclaims all rights. So I do what I like, but perhaps the copyright holder reserves the right to sue me for whatever it is I decide I like to do with their code.
> By contrast, if you decide to sue me for using code you released under an MIT license, the language in that is clear enough that a court can dismiss your suit if what I've done falls under the specific provisions in the license you attached to that code.

Hope this helps to further clear up the silly overly cautious lawyer's concerns, and yes, adding BSD to the README will be very much appreciated.  Thanks for your consideration!

**Comment by ronmamo** [comment] 2017-04-05 18:17
Hey @davemeurer, thanks for sharing the response from your legal apartment. I apologize you as a programmer have to deal with this stupidity, instead of being able to keep on the good work. 

Coders and companies should be able to freely share and use true open source libraries, while lawyers should stay away from genuinely shared source code.

And please let'em know what we think of them: "Fire everyone (start with the lawyers), keep the coders".

**Comment by davemeurer** [comment] 2017-04-05 22:25
Appreciate the sentiments @ronmamo, thank you - totally agree.  Help me understand why it's an issue to add BSD to your readme?  Outside of work, I'm an aspiring OSS programmer and just would like to understand some of the subtleties.

**Comment by crd** [comment] 2017-04-06 21:51
Thought I'd help out and add the BSD license to `COPYING.txt` to make it consistent with the `pom.xml` file: #175

**Comment by davemeurer** [comment] 2017-04-07 12:27
Due to the denied pull request, I'm assuming @ronmamo that BSD isn't an option for this project, correct?  Just wanted to confirm before I decided to pursue another project due to the issue with legal above.  

On a personal note, I'd still be interested in your thoughts why WTFPL is preferred over BSD.  I didn't find much in terms of research, expect from a recommended rejection from the OSI: https://opensource.org/minutes20090304

Appreciate the previous consideration and insight!!

**Comment by ronmamo** [comment] 2017-04-07 13:21
Appreciate your thoughts and motivation, @crd and @davemeurer.

@davemeurer, On a personal note, my interest _here_ is mainly to shed some light on the true meaning of free and open source, and to bring into conscious the stupidity behind this issue. I've tried to read the link you provided in the previous comment. What a horror. Let'em have their stupid meetings and conversations, while we happily continue to contribute to the Open Source movement. So, on a personal note, I'm interested in your thoughts why WTFPL is rejected.

Please let us know what similar projects you find that better suits your needs, I'll be happy to link it from the main page. Also feel free to fork this project and change the license/anything as you will. As it says, you can do whatever you want to. That sounds like a win win for me.

**Comment by spectejb** [comment] 2017-04-07 14:07
@ronmamo - For one reason it was rejected, see my February 6th post.  Adding BSD to the readme accomplishes everything you want for your project and the open source movement in general.  :)

**Comment by pdwaynemiller** [comment] 2017-04-07 14:47
@ronmamo - my interest in commenting in this issue is purely selfish.  I have devoted a lot of time and effort incorporating the 'mongobee' package into my project.  And am now being told that I need to refactor my code to use a different data migration package.  The reason?  'mongobee' uses your 'reflections' library.  I checked mvnrepository and found that 1166 artifacts use 'reflections'.  It would certainly help me if you could update the REAME to include your alternate license and release an update.  I know it seems an absurd reason for a release, but it might just help a lot of us developers.

Please.

**Comment by davemeurer** [comment] 2017-04-07 19:28
Thanks for the fork suggestion @ronmamo!  In terms of my thoughts on why it was rejected, I had trouble understanding it as well, something about Europe not having Public domain.  It made my head hurt!  Only thing I can kind of understand from legal is the license does not provide rights over the code, just the "license document" itself.  If there was a line in the license that read, "do whatever the fuck you want with this code", then I think that would do it.  As is, legal is saying the code is proprietary because there is no license governing the code.  I dunno!  Appreciate the discussions!!

**Comment by davemeurer** [comment] 2017-04-07 20:46
Hey @ronmamo, another thought just occurred to me.  If you add the following warranty clause from the http://www.wtfpl.net/faq/, I wonder if that would solve a lot of issues.  I'll check with my legal and let you know:

> /* This program is free software. It comes without any warranty, to
     * the extent permitted by applicable law. You can redistribute it
     * and/or modify it under the terms of the Do What The Fuck You Want
     * To Public License, Version 2, as published by Sam Hocevar. See
     * http://www.wtfpl.net/ for more details. */

**Comment by pdwaynemiller** [comment] 2017-04-10 13:03
I was brought into this discussion because of some OSS compliance scanning software that flagged the inclusion of your reflections library in my application.  The scanning software also fails the build.  So I'm stuck with refactoring.

Help others... drop the WTFPL.  It is a self referencing license that does nothing for your code.

**Comment by crd** [comment] 2017-04-10 13:17
I understand where @ronmamo is coming from -- he's trying to do the right thing and share his code with the world without restriction or seemingly unnecessary lawyerly input.

Unfortunately the realities of the legal system in the US and elsewhere prevent many of us from using his library.

**Comment by samhocevar** [comment] 2017-04-10 14:10
Hi @ronmamo, I think @davemeurer has a point. As it is right now, the code is quite unclear as to which parts are actually covered by the WTFPL.

**Comment by davemeurer** [comment] 2017-04-11 15:42
Thanks for the suggestion to fork @ronmamo, but I'm hearing that won't be acceptable as it needs to be the original copyright holder, which assuming is you, who needs to license the original program.  And due to the nature of the WTFPL only mentioning "this license document", and not the code, then we are at an impasse.  It doesn't sound like the warranty clause will help, and the only thing that would work is to dual license to a mainstream permissive license.

I did a bit of research and found other popular WTFPL licensed programs, and those authors decided to dual license (or change the license) as well:

Sinon-chai: Dual licensed with BSD: https://github.com/domenic/sinon-chai
Xml-name-validator: licensed changed to Apache 2.0 on Jan29th: https://github.com/jsdom/xml-name-validator/blob/master/LICENSE.txt
Path-is-inside: dual licensed with MIT https://github.com/domenic/path-is-inside/blob/master/LICENSE.txt
Uri-path: Dual licensed with MIT: https://github.com/UltCombo/uri-path/blob/master/LICENSE-MIT

Any chance you can reconsider?

**Comment by davemeurer** [comment] 2017-04-12 22:48
Hi @ronmamo, another possibility I just heard from legal was if you could provide written confirmation that you grant the use of this program under either the BSD, MIT, the Unlicense (http://unlicense.org/), or even the CC0 (https://creativecommons.org/share-your-work/public-domain/cc0/), that would work.  So, you won't have to update the readme, it could just be part of this thread or something else.  If you would like to chat more, please email me at windydavemeurer@gmail.com.  Appreciate the continued dialog!

**Comment by pdwaynemiller** [comment] 2017-04-14 14:41
Hi @samhocevar,  I have not seen any feedback from you regarding the possible issues with the WTFPL.  There are several posts that say the problem with the license is that the text of the license only grants freedom to work with the license itself not the work that it is applied to.  Thoughts?

@ronmamo, I too would be able to use a separate, specific release from you to use, modify, redistribute without restriction or attribution... but that seems a bit overkill.  I will take it it you provide it, but it seems there are simpler options available that would do what you want to accomplish for all developers who want to use the library/source.

I do appreciate what you are trying to do here... and the work you have done.  Thank you.

**Comment by samhocevar** [comment] 2017-04-14 17:58
@pdwaynemiller I believe these concerns are pretty much covered by [the very first FAQ](http://www.wtfpl.net/faq/).

**Comment by pdwaynemiller** [comment] 2017-04-14 19:57
@samhocevar -  I've read the FAQ, read all of the feedback on the site.  Fun to read.  But it is still not clear from the license, that part three applies to the work being released under the license.  One must review the FAQ to see this connection... and the FAQ is not part of the license.  I'm no lawyer, nor did I stay in a Holiday Inn Express last night... but I think the license should be able to stand on its own... no F<sup>2</sup>AQ required.

**Comment by davemeurer** [comment] 2017-04-17 12:33
@ronmamo any thoughts on the latest thread?

@pdwaynemiller - I could be wrong, but I believe the intent of this license wasn't specifically for code, and therefore, it should be up to the developer to modify the license (which is specified by the license) and grant the use of the program.  The license says you must change the name, so I would imagine a license called: "DO WHAT THE FUCK YOU WANT WITH THIS CODE", and then the license would stand on itself with the rights to modify, distribute, etc - maybe even copying the BSD paragraph.

Am I interpreting that correctly, @samhocevar?

**Comment by crd** [comment] 2017-04-17 13:52
Lawyers are preventing developers from using these libraries because of vague or otherwise insufficient licensing -- I'm no lawyer but doubt any amount of tinkering with the WTFPL will suffice. Short of dual-licensing using a more accepted option like BSD/MIT/CC0 I think developers working in corporate environments are left with no choice but to abandon reflections and move to an alternative library.

**Comment by davemeurer** [comment] 2017-04-19 20:06
@ronmamo Would it be possible for you to reply and state: "feel free to fork this project under the BSD license"?

I know, I know... you've mentioned we could fork it and change the license, but what I'm hearing now is this is all we need to move forward.  Please don't shoot the messenger! Hoping one day we can meet up, have a beer, and laugh about all this!! ;-)

**Comment by ronmamo** [comment] 2017-04-20 06:34
@crd Thanks for your thoughts. There are corporate using this library and others without any problem. it is not a matter of a company size, but a matter of a culture and healthy rational.
Keep it lean, keep it logic, keep the lawyers away.

@davemeurer As stated few times before, you can do what the fuck you want to, including forking it and changing anything. This is what the FAQ also states. I think it is a matter of laziness from your legal department. So, "Feel free to do what the fuck you want to, including forking the project under any fucking license.". This is pathetic, isn't it? And a good laugh indeed. Contact me via email if you need a clearer statement. 

The purpose of this thread is not to make life hard on any developer or company, but to raise the attention for a healthy, productive and lean development environment and open source.

**Comment by davemeurer** [comment] 2017-04-20 11:56
Thanks for your patience @ronmamo!  Email sent.

**Comment by rtomsick** [comment] 2017-05-03 15:51
I'd like to join in here to echo the sentiment of some of the other folks in this thread.

Despite your intentions, the license choice is actually *preventing* me (and I suspect others) from using this library.  Sorry, but that's the truth.

There is a time for idealism and a time for pragmatism.  When "taking a stand" to "keep lawyers away" starts *preventing* open source advocates from using your software in organizations that are themselves supporters and creators of open source... well... at that point you're not just keeping away lawyers.  You're keeping away users and developers.

Consider for a moment if that is an ideal outcome for an open source project.

**Comment by stevesea** [comment] 2017-05-03 18:06
For many developers, it's not a simple choice of using org.reflections or not. 

Many developers are using reflections because it's a transitive dependency of some other library/framework they've selected. To name just a couple... anyone using Swagger JAX-RS, the Play! Framework, or Mule are now exposed.

Having the dual-license WTFPL/BSD license mentioned in the POM is enough for some, but it's not enough for all projects. The POM says the project is dual licensed, having the BSD license text in the repo would clarify your intentions.

**Comment by andrewfinnell** [comment] 2018-10-11 15:59
This is the sadest conversation I’ve seen in quite some time. It clearly ignores the fact that the author of any work is automatically the sole copyright holder unless a license says otherwise. And the “License” for the WTFPL is written such that only the license file itself falls under the WTFPL clause. This is basically the same issue with the FSF calling GPL open source and free. It’s not. And neither is this WTFPL license. It’s useless. It effectively sticks ones head in the sound and stomps around in a childish manor while yelling “I’m not listening.”

It’s the antithesis to being Pragmatic. I feel that part of my soul has withered aaay after reading the responses to this repos owner and maintainer. 

It’s all summed up by them moving to GitLab because of Microsoft potentially purchasing GitHub. Despite the fact that we all likely use open source software form Microsoft now. And they’ve become one of the dominating forces in the OSS movement. 

It’s quite ironic this is still written in Java despite it being owned by Oracle. And Oracle requiring licenses to use their JVM now.

A sad sad day.

**Closed** 2018-11-02 03:08 UTC
